Features/food orders
meeorder/meeorder-backend pull request #15
Opened 2023-07-24 18:06 UTC by Vjumpkung

Follwing this features is finished and reviewable
- create database schema 
- create POST request /orders

Disclaimer : this endpoint is not finished because wait table collection and menu collection
- List Orders by session [/sessions/:id/orders]
```ts
response.table = randomInt(1, 10); //wait Table
response.total_price = randomInt(1, 1000); // wait Menu
```
this following two lines is only mock data for test response only

example response
```json
{
    "table": 9,
    "total_price": 91,
    "discount_price": 0,
    "net_price": 91,
    "orders": [
        {
            "_id": "64bea1949f1fe25d5d00368f",
            "created_at": "2023-07-24T16:06:13.142Z",
            "status": "IN_QUEUE",
            "session": "64b95d8869ac259060ac2c6e",
            "menu": "64b963027d0c7729a48d8f67",
            "addons": [
                "64b963047d0c7729a48d8f6b",
                "64b963047d0c7729a48d8f6b"
            ],
            "additional_info": "xxx",
            "__v": 0
        },
        {
            "_id": "64bea1949f1fe25d5d003690",
            "created_at": "2023-07-24T16:06:13.142Z",
            "status": "IN_QUEUE",
            "session": "64b95d8869ac259060ac2c6e",
            "menu": "64b963047d0c7729a48d8f6f",
            "addons": [
                "64b963047d0c7729a48d8f6b",
                "64b963047d0c7729a48d8f6d"
            ],
            "additional_info": "bbb",
            "__v": 0
        },
        {
            "_id": "64bea3059c7b3a1c566692ba",
            "created_at": "2023-07-24T16:12:11.533Z",
            "status": "IN_QUEUE",
            "session": "64b95d8869ac259060ac2c6e",
            "menu": "64b963027d0c7729a48d8f67",
            "addons": [
                "64b963047d0c7729a48d8f6b",
                "64b963047d0c7729a48d8f6b"
            ],
            "additional_info": "yyyyyyyyyxxx",
            "__v": 0
        },
        {
            "_id": "64bea3059c7b3a1c566692bb",
            "created_at": "2023-07-24T16:12:11.533Z",
            "status": "IN_QUEUE",
            "session": "64b95d8869ac259060ac2c6e",
            "menu": "64b963047d0c7729a48d8f6f",
            "addons": [
                "64b963047d0c7729a48d8f6b",
                "64b963047d0c7729a48d8f6d"
            ],
            "additional_info": "bbbxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            "__v": 0
        }
    ]
}
```

2023-07-24 18:08 UTC, Vjumpkung commented
Problems list : 
- in /docs it's cannot add id as params and make id is editable
- 
![image](https://github.com/meeorder/meeorder-backend/assets/12080533/ebab2b70-f60f-48ba-9110-afaa4aa02471)
should I use string or ObjectId becasue annoying '{' <- It's think it is object

2023-07-24 18:40 UTC, hirasawaau requested changes

2023-07-24 18:40 UTC, hirasawaau commented on package.json
> -    "lint:fix": "eslint \"{src,apps,libs,test}/**/*.ts\"",
Why are u remove this script?

2023-07-24 18:40 UTC, hirasawaau commented on package.json
> -    "@typegoose/typegoose": "^11.4.0",
Why delete it?

2023-07-24 18:40 UTC, hirasawaau commented on package.json
> -    "nest-typegoose": "^1.1.1",
Why delete it?

2023-07-24 18:40 UTC, hirasawaau commented on package.json
> +    "mongoose": "^7.3.4",
Why downgrade?

2023-07-24 18:40 UTC, hirasawaau commented on src/schema/categories.schema.ts
> -@modelOptions({ schemaOptions: { collection: 'categories' } })
Use typegoose pls.

2023-07-25 01:53 UTC, Vjumpkung commented
This branch will abandon because I forgot to pull new develop and idk what's happen so I will create new branch instead

2023-07-25 01:53 UTC, closed without merging