E2E/cucumber
meeorder/meeorder-backend pull request #22
Opened 2023-07-27 03:57 UTC by hirasawaau

2023-07-27 04:15 UTC, namirinz commented on .github/workflows/build-test-lint.yml
> +    runs-on: ubuntu-latest]
remove ]

2023-07-27 04:15 UTC, namirinz commented on src/categories/categories.service.ts
Changing in this file should not be in this PR because it's not relevant with E2E or Cucumber but nvm.

2023-07-28 04:24 UTC, hirasawaau commented on src/categories/categories.service.ts
OK,I created pull requested #23 from fix this.

2023-07-28 04:54 UTC, phusitsom requested changes

2023-07-28 04:54 UTC, phusitsom commented on .vscode/launch.json
> +        "MONGODB_NAME": "meeorder"
According to your code in `features/step-definitions/health.ts`, shouldn't this be `MONGO_DB_NAME`?

2023-07-28 04:54 UTC, phusitsom commented on .vscode/launch.json
> +        "MONGODB_NAME": "meeorder"
According to your code in `features/step-definitions/health.ts`, shouldn't this be `MONGO_DB_NAME`?

2023-07-28 05:11 UTC, phusitsom approved these changes

2023-07-28 05:13 UTC, merged