Migrate to yarn
meeorder/meeorder-backend pull request #57
Opened 2023-08-31 16:42 UTC by hirasawaau

# Migrate to Yarn
## Cause
Fastify can't resolve when used `FastifyReply` or `FastifyRequest`, solved with change package manager to yarn
## How to migration
```
npm i -g yarn
```
And use yarn as new package manager in this repo

2023-08-31 17:08 UTC, Vjumpkung commented on package.json
>      "stop:pm2": "pm2 delete 0"
I think it should be name of the process (Backend) 
example `pm2 delete Backend`

2023-08-31 17:09 UTC, vjumpkung requested changes
I suggest a `npm run stop:pm2` one

2023-08-31 17:10 UTC, namirinz approved these changes

2023-08-31 17:16 UTC, namirinz submitted a review, later dismissed
LGTM

2023-08-31 17:17 UTC, Npwskp approved these changes, later dismissed
LGTM !! npm bunzai !!

2023-09-01 10:27 UTC, PraepechPrAe reviewed
Gooo

2023-09-01 10:28 UTC, PraepechPrAe submitted a review, later dismissed
reviewed

2023-09-01 11:08 UTC, merged